### ISSUE TITLE
[medium]BusinessException getMessage 缺失

### ISSUE THREAD

**Issue by cexll** [penghcheng/hyperf-admin#2]
https://github.com/penghcheng/hyperf-admin/blob/45984a73c09d0f64991a78a3df97dbbc127fb22e/app/Exception/BusinessException.php#L24

`ErrorCode::getMessage` 这里是不是有问题呢？

**Comment by penghcheng** [comment]
这个没有问题吧，有什么问题。可以去看看官方的文档也是这么写的。
可以查看一下ErrorCode extends AbstractConstants 



---原始邮件---
发件人: "imorta"<notifications@github.com&gt;
发送时间: 2019年11月21日(星期四) 晚上6:20
收件人: "penghcheng/hyperf-admin"<hyperf-admin@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [penghcheng/hyperf-admin] [medium]BusinessException getMessage 缺失 (#2)



https://github.com/penghcheng/hyperf-admin/blob/45984a73c09d0f64991a78a3df97dbbc127fb22e/app/Exception/BusinessException.php#L24
 
ErrorCode::getMessage 这里是不是有问题呢？

**Comment by cexll** [comment]
官方文档能提供一下吗 谢谢

**Comment by penghcheng** [comment]
https://hyperf.io



---原始邮件---
发件人: "imorta"<notifications@github.com&gt;
发送时间: 2019年11月21日(星期四) 晚上9:03
收件人: "penghcheng/hyperf-admin"<hyperf-admin@noreply.github.com&gt;;
抄送: "penghcheng"<375488452@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题: Re: [penghcheng/hyperf-admin] [medium]BusinessException getMessage 缺失 (#2)



官方文档能提供一下吗 谢谢

**Comment by cexll** [comment]
谢谢 ide点不出来方法 所以为以为是这里有问题，我去官方群问一下 谢谢  你的项目很帮
