### ISSUE TITLE
不是docker环境要怎么用呢

### ISSUE THREAD

**Issue by cjhlai** [penghcheng/hyperf-admin#8]
不是docker环境要怎么用呢

**Comment by penghcheng** [comment]
不是docker也一样的，安装了PHP,swoole，然后对应端口就可以了。



---原始邮件---
发件人: "breeze"<notifications@github.com&gt;
发送时间: 2020年2月9日(周日) 晚上8:55
收件人: "penghcheng/hyperf-admin"<hyperf-admin@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [penghcheng/hyperf-admin] 不是docker环境要怎么用呢 (#8)



不是docker环境要怎么用呢

**Comment by cjhlai** [comment]
好的，谢谢，请问您有在生产环境使用过hyperf吗




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"penghcheng"<notifications@github.com&gt;;
发送时间:&nbsp;2020年2月9日(星期天) 晚上8:56
收件人:&nbsp;"penghcheng/hyperf-admin"<hyperf-admin@noreply.github.com&gt;;
抄送:&nbsp;"景华"<1017890340@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [penghcheng/hyperf-admin] 不是docker环境要怎么用呢 (#8)



不是docker也一样的，安装了PHP,swoole，然后对应端口就可以了。 
 
 
 
 ---原始邮件--- 
 发件人: "breeze"<notifications@github.com&amp;gt; 
 发送时间: 2020年2月9日(周日) 晚上8:55 
 收件人: "penghcheng/hyperf-admin"<hyperf-admin@noreply.github.com&amp;gt;; 
 抄送: "Subscribed"<subscribed@noreply.github.com&amp;gt;; 
 主题: [penghcheng/hyperf-admin] 不是docker环境要怎么用呢 (#8) 
 
 
 
 不是docker环境要怎么用呢

**Comment by penghcheng** [comment]
在用中。



---原始邮件---
发件人: "breeze"<notifications@github.com&gt;
发送时间: 2020年2月9日(周日) 晚上9:07
收件人: "penghcheng/hyperf-admin"<hyperf-admin@noreply.github.com&gt;;
抄送: "penghcheng"<375488452@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题: Re: [penghcheng/hyperf-admin] 不是docker环境要怎么用呢 (#8)


好的，谢谢，请问您有在生产环境使用过hyperf吗 
 
 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人:&amp;nbsp;"penghcheng"<notifications@github.com&amp;gt;; 
 发送时间:&amp;nbsp;2020年2月9日(星期天) 晚上8:56 
 收件人:&amp;nbsp;"penghcheng/hyperf-admin"<hyperf-admin@noreply.github.com&amp;gt;; 
 抄送:&amp;nbsp;"景华"<1017890340@qq.com&amp;gt;;"Author"<author@noreply.github.com&amp;gt;; 
 主题:&amp;nbsp;Re: [penghcheng/hyperf-admin] 不是docker环境要怎么用呢 (#8) 
 
 
 
 不是docker也一样的，安装了PHP,swoole，然后对应端口就可以了。  
   
   
   
  ---原始邮件---  
  发件人: "breeze"<notifications@github.com&amp;amp;gt;  
  发送时间: 2020年2月9日(周日) 晚上8:55  
  收件人: "penghcheng/hyperf-admin"<hyperf-admin@noreply.github.com&amp;amp;gt;;  
  抄送: "Subscribed"<subscribed@noreply.github.com&amp;amp;gt;;  
  主题: [penghcheng/hyperf-admin] 不是docker环境要怎么用呢 (#8)  
   
   
   
  不是docker环境要怎么用呢

**Comment by cjhlai** [comment]
能否加个qq，跟您了解下实际的项目踩坑的情况。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"penghcheng"<notifications@github.com&gt;;
发送时间:&nbsp;2020年2月9日(星期天) 晚上9:10
收件人:&nbsp;"penghcheng/hyperf-admin"<hyperf-admin@noreply.github.com&gt;;
抄送:&nbsp;"景华"<1017890340@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [penghcheng/hyperf-admin] 不是docker环境要怎么用呢 (#8)



在用中。 
 
 
 
 ---原始邮件--- 
 发件人: "breeze"<notifications@github.com&amp;gt; 
 发送时间: 2020年2月9日(周日) 晚上9:07 
 收件人: "penghcheng/hyperf-admin"<hyperf-admin@noreply.github.com&amp;gt;; 
 抄送: "penghcheng"<375488452@qq.com&amp;gt;;"Comment"<comment@noreply.github.com&amp;gt;; 
 主题: Re: [penghcheng/hyperf-admin] 不是docker环境要怎么用呢 (#8) 
 
 
 好的，谢谢，请问您有在生产环境使用过hyperf吗  
   
   
   
   
  ------------------&amp;amp;nbsp;原始邮件&amp;amp;nbsp;------------------  
  发件人:&amp;amp;nbsp;"penghcheng"<notifications@github.com&amp;amp;gt;;  
  发送时间:&amp;amp;nbsp;2020年2月9日(星期天) 晚上8:56  
  收件人:&amp;amp;nbsp;"penghcheng/hyperf-admin"<hyperf-admin@noreply.github.com&amp;amp;gt;;  
  抄送:&amp;amp;nbsp;"景华"<1017890340@qq.com&amp;amp;gt;;"Author"<author@noreply.github.com&amp;amp;gt;;  
  主题:&amp;amp;nbsp;Re: [penghcheng/hyperf-admin] 不是docker环境要怎么用呢 (#8)  
   
   
   
  不是docker也一样的，安装了PHP,swoole，然后对应端口就可以了。   
     
     
     
   ---原始邮件---   
   发件人: "breeze"<notifications@github.com&amp;amp;amp;gt;   
   发送时间: 2020年2月9日(周日) 晚上8:55   
   收件人: "penghcheng/hyperf-admin"<hyperf-admin@noreply.github.com&amp;amp;amp;gt;;   
   抄送: "Subscribed"<subscribed@noreply.github.com&amp;amp;amp;gt;;   
   主题: [penghcheng/hyperf-admin] 不是docker环境要怎么用呢 (#8)   
     
     
     
   不是docker环境要怎么用呢

**Comment by penghcheng** [comment]
可以的。有个QQ群的，上面可以找到我。



---原始邮件---
发件人: "breeze"<notifications@github.com&gt;
发送时间: 2020年2月9日(周日) 晚上9:14
收件人: "penghcheng/hyperf-admin"<hyperf-admin@noreply.github.com&gt;;
抄送: "penghcheng"<375488452@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题: Re: [penghcheng/hyperf-admin] 不是docker环境要怎么用呢 (#8)


能否加个qq，跟您了解下实际的项目踩坑的情况。 
 
 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人:&amp;nbsp;"penghcheng"<notifications@github.com&amp;gt;; 
 发送时间:&amp;nbsp;2020年2月9日(星期天) 晚上9:10 
 收件人:&amp;nbsp;"penghcheng/hyperf-admin"<hyperf-admin@noreply.github.com&amp;gt;; 
 抄送:&amp;nbsp;"景华"<1017890340@qq.com&amp;gt;;"Author"<author@noreply.github.com&amp;gt;; 
 主题:&amp;nbsp;Re: [penghcheng/hyperf-admin] 不是docker环境要怎么用呢 (#8) 
 
 
 
 在用中。  
   
   
   
  ---原始邮件---  
  发件人: "breeze"<notifications@github.com&amp;amp;gt;  
  发送时间: 2020年2月9日(周日) 晚上9:07  
  收件人: "penghcheng/hyperf-admin"<hyperf-admin@noreply.github.com&amp;amp;gt;;  
  抄送: "penghcheng"<375488452@qq.com&amp;amp;gt;;"Comment"<comment@noreply.github.com&amp;amp;gt;;  
  主题: Re: [penghcheng/hyperf-admin] 不是docker环境要怎么用呢 (#8)  
   
   
  好的，谢谢，请问您有在生产环境使用过hyperf吗   
     
     
     
     
   ------------------&amp;amp;amp;nbsp;原始邮件&amp;amp;amp;nbsp;------------------   
   发件人:&amp;amp;amp;nbsp;"penghcheng"<notifications@github.com&amp;amp;amp;gt;;   
   发送时间:&amp;amp;amp;nbsp;2020年2月9日(星期天) 晚上8:56   
   收件人:&amp;amp;amp;nbsp;"penghcheng/hyperf-admin"<hyperf-admin@noreply.github.com&amp;amp;amp;gt;;   
   抄送:&amp;amp;amp;nbsp;"景华"<1017890340@qq.com&amp;amp;amp;gt;;"Author"<author@noreply.github.com&amp;amp;amp;gt;;   
   主题:&amp;amp;amp;nbsp;Re: [penghcheng/hyperf-admin] 不是docker环境要怎么用呢 (#8)   
     
     
     
   不是docker也一样的，安装了PHP,swoole，然后对应端口就可以了。    
       
       
       
    ---原始邮件---    
    发件人: "breeze"<notifications@github.com&amp;amp;amp;amp;gt;    
    发送时间: 2020年2月9日(周日) 晚上8:55    
    收件人: "penghcheng/hyperf-admin"<hyperf-admin@noreply.github.com&amp;amp;amp;amp;gt;;    
    抄送: "Subscribed"<subscribed@noreply.github.com&amp;amp;amp;amp;gt;;    
    主题: [penghcheng/hyperf-admin] 不是docker环境要怎么用呢 (#8)    
       
       
       
    不是docker环境要怎么用呢

**Comment by itxiao6** [comment]
api/Dockerfile 就是docker使用方法 ，部署的话 可以使用docker  或者用K8S做容器编排

**Comment by itxiao6** [comment]
docker build -t api:1.0 api/ 即可编译镜像
运行的 话 可以用docker 运行容器 或者其他的容器编排工具即可
