### ISSUE TITLE
请问数据库表接口在哪里呢？

### ISSUE THREAD

**Issue by jckings2007** [penghcheng/hyperf-admin#9]
在api的根目录下没有migrations目录，也没有找到sql文件

**Comment by penghcheng** [comment]
切换到v1分支



---原始邮件---
发件人: "jckings2007"<notifications@github.com&gt;
发送时间: 2020年5月7日(周四) 上午9:39
收件人: "penghcheng/hyperf-admin"<hyperf-admin@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [penghcheng/hyperf-admin] 请问数据库表接口在哪里呢？ (#9)




 
在api的根目录下没有migrations目录，也没有找到sql文件
